Snd 26
ZanichelliEditore/sendy pull request #230
Opened 2024-05-03 15:17 UTC by valentinavirga

## Pull Request Process

1. Ensure any install or build dependencies are removed before the end of the layer when doing a 
   build.
2. Update the README.md with details of changes to the interface, this includes new environment 
   variables, exposed ports, useful file locations and container parameters.
3. You may merge the Pull Request in once you have the sign-off of two other developers, or if you 
   do not have permission to do that, you may request the second reviewer to merge it for you.

2024-05-07 12:58 UTC, veronicavannini commented on app/Console/Commands/TooManyFailedJobs.php
> +    protected $description = 'Check if failedJobs are more than 100 and send a slack message';
Sarebbe da aggiornare con qualcosa simile a "... are more or equal to 1 ..."

2024-05-07 13:38 UTC, veronicavannini commented on tests/Feature/TooManyFailedJobsCommandTest.php
> +        ];
Ora questo test fallisce, il provider dovrebbe diventare così:
```
return [
            [0, 0],
            [1, 1],
        ];
```

2024-05-07 13:39 UTC, veronicavannini commented on tests/Feature/TooManyFailedJobsCommandTest.php
> +    public function tooManyFailedJobsTest($failedJobsCount, $emailSended)
Qui e sotto sarebbe più appropriato `$notificationSended` al posto di `$emailSended`

2024-05-07 13:53 UTC, veronicavannini commented on app/Notifications/SlackNotification.php
> +    public function toArray($notifiable)
Questo metodo sembra non servire quindi si può togliere

2024-05-07 13:55 UTC, veronicavannini commented on app/Notifications/SlackNotification.php
> +    use Notifiable;
Questi due sembrano non essere usati, si potrebbero togliere sia qui, sia gli import, sia $notifiable nei metodi sotto

2024-05-07 14:18 UTC, veronicavannini approved these changes

2024-05-08 09:51 UTC, mikelina commented on app/Console/Commands/TooManyFailedJobs.php
> +            Notification::route('slack', config('notifications.SLACK_BOT_USER_DEFAULT_CHANNEL'))
Forse si potrebbe mettere che invia le cose su slack solo se ci sono i parametri nell'env? Visto che è un progetto su github pubblico potremmo anche aggiungere qualcosa nel readme che spiega che configurando i parametri di slack nell'env allora ogni 15 minuti viene fatto un controllo e inviata una notifica.

2024-05-15 14:21 UTC, saldomik requested changes

2024-05-15 14:21 UTC, saldomik commented on composer.lock
> +    "plugin-api-version": "2.6.0"
Questa serve ancora?

2024-05-15 14:36 UTC, saldomik commented on app/Console/Commands/TooManyFailedJobs.php
> +        $failedJobsCount = $this->failedJobRepository->count();
Questa `count` potrebbe generare una QueryException direi, la metterei nel try e catcherei la possibile eccezione.

2024-05-21 10:09 UTC, veronicavannini commented on tests/Feature/TooManyFailedJobsCommandTest.php
> +    public function tooManyFailedJobsTest($failedJobsCount, $times)
Falliscono i test

2024-05-21 10:45 UTC, veronicavannini commented on app/Console/Commands/TooManyFailedJobs.php
> +        if (!config('services.slackk.notifications'))
C'è una doppia 'k', dovrebbe diventare:
`if (!config('services.slack.notifications'))`

2024-05-21 14:09 UTC, veronicavannini approved these changes

2024-05-21 15:59 UTC, saldomik approved these changes

2024-06-05 12:08 UTC, merged